version: '3.4'

services:
  web:
    networks:
      - internet
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    container_name: sqlserver
    image: sql-server
    restart: always
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - 1433:1433
    build: 
      context: .
      dockerfile: sqlserver/Dockerfile
    networks:
      - internet
      
networks:
  internet:
